### ISSUE TITLE
bower install ECONFLICT

### ISSUE THREAD

**Issue by leotm** [devanp92/scotch-io#2]
`npm install` in root.
`bower install` in root.

![capture](https://user-images.githubusercontent.com/1881059/28271810-e383a928-6b09-11e7-890c-1afd9ba16968.PNG)

**Comment by devanp92** [comment]
@leotm, thanks for posting the issue! I haven't made any changes in over 2 years to this repository - if you would like to submit a fix, that'd be greatly appreciated!

**Comment by leotm** [comment]
I honestly tried the scotch.io tutorial for many hours, including reading all the comments and trying the suggestions; after much headache, still couldn't get it up and running.

Just a suggestion: I would highly recommend taking down the tutorial, until it's fully corrected and fixed with a working bug-free repo.

I've had no issues with TodoMVC (VanillaJS) and Angular4/AngularFire2/Firebase/Bootstrap4, so I wouldn't think it's just me.

Cheers.

**Comment by devanp92** [comment]
I think this tutorial still holds informational value. I will add a warning in the README.
